server:
  port: 9297

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edmundszagars/document-server-config.git
          clone-on-start: true